# Generated by Django 5.1.3 on 2024-12-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gladiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('health', models.IntegerField()),
                ('attackPower', models.IntegerField()),
                ('specialMoveChance', models.FloatField()),
                ('subclass', models.CharField(max_length=50)),
                ('imagePath', models.URLField()),
            ],
        ),
    ]
